apiVersion: v1
kind: ReplicationController ####type of RC
metadata:
  name: mytest ####name of RC, unique
spec:
  replicas: 1 ####Num of copy for Pod
  selector:
    app: mytest ####expected label for Pod
  template: ####Pod instance
    metadata:
      labels:
         app: mytest ####label for Pod copy
    spec:
      containers: ####def of container in Pod
        - name: mytest ####container name
          image: 192.168.186.159:5000/ubuntu-go-20190313002 ####container img
          imagePullPolicy: IfNotPresent
          tty: true ####To keep the container active, you must exec at least one continuously running task or set tty=true
          volumeMounts:
            - mountPath: "/test/my-pvc"
              name: my-pvc
      volumes:
        - name: my-pvc
          persistentVolumeClaim:
            claimName: pvc-test
