apiVersion: v1
kind: Service
metadata:
  name: myweb ####name of Service, unique
spec:
  type: NodePort ####can be accessed from outside
  ports:
  - port: 8080 ####port of service, open to pub
    nodePort: 30001 ####get access to Service vir port 30001 from outside, mapping to 8080 internal
  selector:
    app: myweb ####label for Pod
