apiVersion: v1
kind: ReplicationController ####type of RC
metadata:
  name: myweb ####name of RC, unique
spec:
  replicas: 5 ####Num of copy for Pod
  selector:
    app: myweb ####expected label for Pod
  template: ####Pod instance
    metadata:
      labels:
         app: myweb ####label for Pod copy
    spec:
      containers: ####def of container in Pod
      - name: myweb ####container name
        image: kubeguide/tomcat-app:v1 ####container img
        ports:
        - containerPort: 8080
        env: ####env params in container
        - name: MYSQL_SERVICE_HOST
          value: 'mysql'
        - name: MYSQL_SERVICE_PORT
          value: '3306'

