apiVersion: v1
kind: ReplicationController ####type of RC
metadata:
  name: my-cicd ####name of RC, unique
spec:
  replicas: 1 ####Num of copy for Pod
  selector:
    app: my-cicd ####expected label for Pod
  template: ####Pod instance
    metadata:
      labels:
        app: my-cicd ####label for Pod copy
    spec:
      containers: ####def of container in Pod
      - name: gitlab ####container name
        image: gitlab/gitlab-ce ####container img
        imagePullPolicy: IfNotPresent
        tty: true ####To keep the container active, you must exec at least one continuously running task or set tty=true
        ports:
        - containerPort: 443
        - containerPort: 80


